#!/bin/bash

python EventDisplay.py --cham   1 --list <(echo "223" ) --file ../test.root
python EventDisplay.py --cham   2 --list <(echo "223" ) --file ../test.root
python EventDisplay.py --cham   3 --list <(echo "461" ) --file ../test.root
python EventDisplay.py --cham   4 --list <(echo "303" ) --file ../test.root
python EventDisplay.py --cham   5 --list <(echo "303" ) --file ../test.root
python EventDisplay.py --cham   6 --list <(echo "140" ) --file ../test.root
python EventDisplay.py --cham   7 --list <(echo "21"  ) --file ../test.root
python EventDisplay.py --cham   8 --list <(echo "315" ) --file ../test.root
python EventDisplay.py --cham   9 --list <(echo "208" ) --file ../test.root
python EventDisplay.py --cham  10 --list <(echo "9"   ) --file ../test.root
python EventDisplay.py --cham  11 --list <(echo "30"  ) --file ../test.root
python EventDisplay.py --cham  12 --list <(echo "431" ) --file ../test.root
python EventDisplay.py --cham  13 --list <(echo "440" ) --file ../test.root
python EventDisplay.py --cham  14 --list <(echo "259" ) --file ../test.root
python EventDisplay.py --cham  15 --list <(echo "1116") --file ../test.root
python EventDisplay.py --cham  16 --list <(echo "223" ) --file ../test.root
python EventDisplay.py --cham  17 --list <(echo "88"  ) --file ../test.root
python EventDisplay.py --cham  18 --list <(echo "705" ) --file ../test.root
python EventDisplay.py --cham  19 --list <(echo "569" ) --file ../test.root
python EventDisplay.py --cham  20 --list <(echo "125" ) --file ../test.root
python EventDisplay.py --cham  21 --list <(echo "7"   ) --file ../test.root
python EventDisplay.py --cham  22 --list <(echo "7"   ) --file ../test.root
python EventDisplay.py --cham  23 --list <(echo "132" ) --file ../test.root
python EventDisplay.py --cham  24 --list <(echo "132" ) --file ../test.root
python EventDisplay.py --cham  25 --list <(echo "55"  ) --file ../test.root
python EventDisplay.py --cham  26 --list <(echo "149" ) --file ../test.root
python EventDisplay.py --cham  27 --list <(echo "512" ) --file ../test.root
python EventDisplay.py --cham  28 --list <(echo "566" ) --file ../test.root
python EventDisplay.py --cham  29 --list <(echo "673" ) --file ../test.root
python EventDisplay.py --cham  30 --list <(echo "30"  ) --file ../test.root
python EventDisplay.py --cham  31 --list <(echo "30"  ) --file ../test.root
python EventDisplay.py --cham  32 --list <(echo "916" ) --file ../test.root
python EventDisplay.py --cham  33 --list <(echo "411" ) --file ../test.root
python EventDisplay.py --cham  34 --list <(echo "411" ) --file ../test.root
python EventDisplay.py --cham  35 --list <(echo "287" ) --file ../test.root
python EventDisplay.py --cham  36 --list <(echo "407" ) --file ../test.root
python EventDisplay.py --cham  37 --list <(echo "951" ) --file ../test.root
python EventDisplay.py --cham  38 --list <(echo "132" ) --file ../test.root
python EventDisplay.py --cham  39 --list <(echo "125" ) --file ../test.root
python EventDisplay.py --cham  40 --list <(echo "106" ) --file ../test.root
python EventDisplay.py --cham  41 --list <(echo "59"  ) --file ../test.root
python EventDisplay.py --cham  42 --list <(echo "543" ) --file ../test.root
python EventDisplay.py --cham  43 --list <(echo "310" ) --file ../test.root
python EventDisplay.py --cham  44 --list <(echo "79"  ) --file ../test.root
python EventDisplay.py --cham  45 --list <(echo "149" ) --file ../test.root
python EventDisplay.py --cham  46 --list <(echo "636" ) --file ../test.root
python EventDisplay.py --cham  47 --list <(echo "607" ) --file ../test.root
python EventDisplay.py --cham  48 --list <(echo "40"  ) --file ../test.root
python EventDisplay.py --cham  49 --list <(echo "650" ) --file ../test.root
python EventDisplay.py --cham  50 --list <(echo "476" ) --file ../test.root
python EventDisplay.py --cham  51 --list <(echo "719" ) --file ../test.root
python EventDisplay.py --cham  52 --list <(echo "247" ) --file ../test.root
python EventDisplay.py --cham  53 --list <(echo "1559") --file ../test.root
python EventDisplay.py --cham  54 --list <(echo "672" ) --file ../test.root
python EventDisplay.py --cham  55 --list <(echo "723" ) --file ../test.root
python EventDisplay.py --cham  56 --list <(echo "240" ) --file ../test.root
python EventDisplay.py --cham  57 --list <(echo "240" ) --file ../test.root
python EventDisplay.py --cham  58 --list <(echo "461" ) --file ../test.root
python EventDisplay.py --cham  59 --list <(echo "1266") --file ../test.root
python EventDisplay.py --cham  60 --list <(echo "303" ) --file ../test.root
python EventDisplay.py --cham  61 --list <(echo "221" ) --file ../test.root
python EventDisplay.py --cham  62 --list <(echo "259" ) --file ../test.root
python EventDisplay.py --cham  63 --list <(echo "273" ) --file ../test.root
python EventDisplay.py --cham  64 --list <(echo "875" ) --file ../test.root
python EventDisplay.py --cham  65 --list <(echo "315" ) --file ../test.root
python EventDisplay.py --cham  66 --list <(echo "266" ) --file ../test.root
python EventDisplay.py --cham  67 --list <(echo "668" ) --file ../test.root
python EventDisplay.py --cham  68 --list <(echo "636" ) --file ../test.root
python EventDisplay.py --cham  69 --list <(echo "1575") --file ../test.root
python EventDisplay.py --cham  70 --list <(echo "1079") --file ../test.root
python EventDisplay.py --cham  71 --list <(echo "1116") --file ../test.root
python EventDisplay.py --cham  72 --list <(echo "462" ) --file ../test.root
python EventDisplay.py --cham  73 --list <(echo "361" ) --file ../test.root
python EventDisplay.py --cham  74 --list <(echo "216" ) --file ../test.root
python EventDisplay.py --cham  75 --list <(echo "7"   ) --file ../test.root
python EventDisplay.py --cham  76 --list <(echo "588" ) --file ../test.root
python EventDisplay.py --cham  77 --list <(echo "55"  ) --file ../test.root
python EventDisplay.py --cham  78 --list <(echo "565" ) --file ../test.root
python EventDisplay.py --cham  79 --list <(echo "433" ) --file ../test.root
python EventDisplay.py --cham  80 --list <(echo "1343") --file ../test.root
python EventDisplay.py --cham  81 --list <(echo "958" ) --file ../test.root
python EventDisplay.py --cham  82 --list <(echo "481" ) --file ../test.root
python EventDisplay.py --cham  83 --list <(echo "126" ) --file ../test.root
python EventDisplay.py --cham  84 --list <(echo "136" ) --file ../test.root
python EventDisplay.py --cham  85 --list <(echo "417" ) --file ../test.root
python EventDisplay.py --cham  86 --list <(echo "1643") --file ../test.root
python EventDisplay.py --cham  89 --list <(echo "145" ) --file ../test.root
python EventDisplay.py --cham  90 --list <(echo "163" ) --file ../test.root
python EventDisplay.py --cham  91 --list <(echo "786" ) --file ../test.root
python EventDisplay.py --cham  92 --list <(echo "1057") --file ../test.root
python EventDisplay.py --cham  93 --list <(echo "1046") --file ../test.root
python EventDisplay.py --cham  94 --list <(echo "59"  ) --file ../test.root
python EventDisplay.py --cham  95 --list <(echo "435" ) --file ../test.root
python EventDisplay.py --cham  96 --list <(echo "1252") --file ../test.root
python EventDisplay.py --cham  97 --list <(echo "460" ) --file ../test.root
python EventDisplay.py --cham 100 --list <(echo "208" ) --file ../test.root
python EventDisplay.py --cham 101 --list <(echo "116" ) --file ../test.root
python EventDisplay.py --cham 102 --list <(echo "9"   ) --file ../test.root
python EventDisplay.py --cham 103 --list <(echo "262" ) --file ../test.root
python EventDisplay.py --cham 104 --list <(echo "434" ) --file ../test.root
python EventDisplay.py --cham 105 --list <(echo "4"   ) --file ../test.root
python EventDisplay.py --cham 106 --list <(echo "34"  ) --file ../test.root
python EventDisplay.py --cham 107 --list <(echo "873" ) --file ../test.root
python EventDisplay.py --cham 109 --list <(echo "223" ) --file ../test.root
python EventDisplay.py --cham 110 --list <(echo "461" ) --file ../test.root
python EventDisplay.py --cham 111 --list <(echo "140" ) --file ../test.root
python EventDisplay.py --cham 112 --list <(echo "21"  ) --file ../test.root
python EventDisplay.py --cham 113 --list <(echo "9"   ) --file ../test.root
python EventDisplay.py --cham 114 --list <(echo "30"  ) --file ../test.root
python EventDisplay.py --cham 115 --list <(echo "259" ) --file ../test.root
python EventDisplay.py --cham 116 --list <(echo "462" ) --file ../test.root
python EventDisplay.py --cham 117 --list <(echo "88"  ) --file ../test.root
python EventDisplay.py --cham 118 --list <(echo "569" ) --file ../test.root
python EventDisplay.py --cham 119 --list <(echo "7"   ) --file ../test.root
python EventDisplay.py --cham 120 --list <(echo "132" ) --file ../test.root
python EventDisplay.py --cham 121 --list <(echo "55"  ) --file ../test.root
python EventDisplay.py --cham 122 --list <(echo "512" ) --file ../test.root
python EventDisplay.py --cham 123 --list <(echo "30"  ) --file ../test.root
python EventDisplay.py --cham 124 --list <(echo "30"  ) --file ../test.root
python EventDisplay.py --cham 125 --list <(echo "411" ) --file ../test.root
python EventDisplay.py --cham 126 --list <(echo "287" ) --file ../test.root
python EventDisplay.py --cham 127 --list <(echo "160" ) --file ../test.root
python EventDisplay.py --cham 128 --list <(echo "132" ) --file ../test.root
python EventDisplay.py --cham 129 --list <(echo "125" ) --file ../test.root
python EventDisplay.py --cham 130 --list <(echo "106" ) --file ../test.root
python EventDisplay.py --cham 131 --list <(echo "55"  ) --file ../test.root
python EventDisplay.py --cham 132 --list <(echo "543" ) --file ../test.root
python EventDisplay.py --cham 133 --list <(echo "310" ) --file ../test.root
python EventDisplay.py --cham 134 --list <(echo "79"  ) --file ../test.root
python EventDisplay.py --cham 135 --list <(echo "149" ) --file ../test.root
python EventDisplay.py --cham 136 --list <(echo "515" ) --file ../test.root
python EventDisplay.py --cham 137 --list <(echo "607" ) --file ../test.root
python EventDisplay.py --cham 138 --list <(echo "40"  ) --file ../test.root
python EventDisplay.py --cham 139 --list <(echo "673" ) --file ../test.root
python EventDisplay.py --cham 140 --list <(echo "476" ) --file ../test.root
python EventDisplay.py --cham 141 --list <(echo "719" ) --file ../test.root
python EventDisplay.py --cham 142 --list <(echo "247" ) --file ../test.root
python EventDisplay.py --cham 143 --list <(echo "145" ) --file ../test.root
python EventDisplay.py --cham 144 --list <(echo "163" ) --file ../test.root
python EventDisplay.py --cham 145 --list <(echo "723" ) --file ../test.root
python EventDisplay.py --cham 146 --list <(echo "640" ) --file ../test.root
python EventDisplay.py --cham 147 --list <(echo "473" ) --file ../test.root
python EventDisplay.py --cham 148 --list <(echo "59"  ) --file ../test.root
python EventDisplay.py --cham 149 --list <(echo "435" ) --file ../test.root
python EventDisplay.py --cham 150 --list <(echo "303" ) --file ../test.root
python EventDisplay.py --cham 151 --list <(echo "221" ) --file ../test.root
python EventDisplay.py --cham 152 --list <(echo "95"  ) --file ../test.root
python EventDisplay.py --cham 153 --list <(echo "273" ) --file ../test.root
python EventDisplay.py --cham 154 --list <(echo "187" ) --file ../test.root
python EventDisplay.py --cham 155 --list <(echo "315" ) --file ../test.root
python EventDisplay.py --cham 156 --list <(echo "9"   ) --file ../test.root
python EventDisplay.py --cham 157 --list <(echo "106" ) --file ../test.root
python EventDisplay.py --cham 158 --list <(echo "434" ) --file ../test.root
python EventDisplay.py --cham 159 --list <(echo "1158") --file ../test.root
python EventDisplay.py --cham 160 --list <(echo "34"  ) --file ../test.root
python EventDisplay.py --cham 161 --list <(echo "322" ) --file ../test.root
python EventDisplay.py --cham 162 --list <(echo "3"   ) --file ../test.root
python EventDisplay.py --cham 163 --list <(echo "223" ) --file ../test.root
python EventDisplay.py --cham 164 --list <(echo "461" ) --file ../test.root
python EventDisplay.py --cham 165 --list <(echo "140" ) --file ../test.root
python EventDisplay.py --cham 166 --list <(echo "140" ) --file ../test.root
python EventDisplay.py --cham 167 --list <(echo "9"   ) --file ../test.root
python EventDisplay.py --cham 168 --list <(echo "30"  ) --file ../test.root
python EventDisplay.py --cham 169 --list <(echo "259" ) --file ../test.root
python EventDisplay.py --cham 170 --list <(echo "462" ) --file ../test.root
python EventDisplay.py --cham 171 --list <(echo "88"  ) --file ../test.root
python EventDisplay.py --cham 172 --list <(echo "569" ) --file ../test.root
python EventDisplay.py --cham 173 --list <(echo "7"   ) --file ../test.root
python EventDisplay.py --cham 174 --list <(echo "132" ) --file ../test.root
python EventDisplay.py --cham 175 --list <(echo "55"  ) --file ../test.root
python EventDisplay.py --cham 176 --list <(echo "512" ) --file ../test.root
python EventDisplay.py --cham 177 --list <(echo "30"  ) --file ../test.root
python EventDisplay.py --cham 178 --list <(echo "30"  ) --file ../test.root
python EventDisplay.py --cham 179 --list <(echo "411" ) --file ../test.root
python EventDisplay.py --cham 180 --list <(echo "287" ) --file ../test.root
python EventDisplay.py --cham 181 --list <(echo "160" ) --file ../test.root
python EventDisplay.py --cham 182 --list <(echo "132" ) --file ../test.root
python EventDisplay.py --cham 183 --list <(echo "125" ) --file ../test.root
python EventDisplay.py --cham 184 --list <(echo "106" ) --file ../test.root
python EventDisplay.py --cham 185 --list <(echo "55"  ) --file ../test.root
python EventDisplay.py --cham 186 --list <(echo "543" ) --file ../test.root
python EventDisplay.py --cham 187 --list <(echo "310" ) --file ../test.root
python EventDisplay.py --cham 188 --list <(echo "79"  ) --file ../test.root
python EventDisplay.py --cham 189 --list <(echo "149" ) --file ../test.root
python EventDisplay.py --cham 190 --list <(echo "636" ) --file ../test.root
python EventDisplay.py --cham 191 --list <(echo "607" ) --file ../test.root
python EventDisplay.py --cham 192 --list <(echo "40"  ) --file ../test.root
python EventDisplay.py --cham 193 --list <(echo "650" ) --file ../test.root
python EventDisplay.py --cham 194 --list <(echo "476" ) --file ../test.root
python EventDisplay.py --cham 195 --list <(echo "719" ) --file ../test.root
python EventDisplay.py --cham 196 --list <(echo "247" ) --file ../test.root
python EventDisplay.py --cham 197 --list <(echo "1559") --file ../test.root
python EventDisplay.py --cham 198 --list <(echo "672" ) --file ../test.root
python EventDisplay.py --cham 199 --list <(echo "723" ) --file ../test.root
python EventDisplay.py --cham 200 --list <(echo "240" ) --file ../test.root
python EventDisplay.py --cham 201 --list <(echo "240" ) --file ../test.root
python EventDisplay.py --cham 202 --list <(echo "397" ) --file ../test.root
python EventDisplay.py --cham 203 --list <(echo "1208") --file ../test.root
python EventDisplay.py --cham 204 --list <(echo "303" ) --file ../test.root
python EventDisplay.py --cham 205 --list <(echo "221" ) --file ../test.root
python EventDisplay.py --cham 206 --list <(echo "95"  ) --file ../test.root
python EventDisplay.py --cham 207 --list <(echo "273" ) --file ../test.root
python EventDisplay.py --cham 208 --list <(echo "187" ) --file ../test.root
python EventDisplay.py --cham 209 --list <(echo "315" ) --file ../test.root
python EventDisplay.py --cham 210 --list <(echo "266" ) --file ../test.root
python EventDisplay.py --cham 211 --list <(echo "106" ) --file ../test.root
python EventDisplay.py --cham 212 --list <(echo "636" ) --file ../test.root
python EventDisplay.py --cham 213 --list <(echo "1575") --file ../test.root
python EventDisplay.py --cham 214 --list <(echo "1079") --file ../test.root
python EventDisplay.py --cham 215 --list <(echo "322" ) --file ../test.root
python EventDisplay.py --cham 216 --list <(echo "462" ) --file ../test.root
python EventDisplay.py --cham 217 --list <(echo "223" ) --file ../test.root
python EventDisplay.py --cham 218 --list <(echo "461" ) --file ../test.root
python EventDisplay.py --cham 219 --list <(echo "140" ) --file ../test.root
python EventDisplay.py --cham 220 --list <(echo "140" ) --file ../test.root
python EventDisplay.py --cham 221 --list <(echo "9"   ) --file ../test.root
python EventDisplay.py --cham 222 --list <(echo "116" ) --file ../test.root
python EventDisplay.py --cham 223 --list <(echo "259" ) --file ../test.root
python EventDisplay.py --cham 224 --list <(echo "462" ) --file ../test.root
python EventDisplay.py --cham 225 --list <(echo "223" ) --file ../test.root
python EventDisplay.py --cham 226 --list <(echo "569" ) --file ../test.root
python EventDisplay.py --cham 227 --list <(echo "7"   ) --file ../test.root
python EventDisplay.py --cham 228 --list <(echo "132" ) --file ../test.root
python EventDisplay.py --cham 229 --list <(echo "149" ) --file ../test.root
python EventDisplay.py --cham 230 --list <(echo "512" ) --file ../test.root
python EventDisplay.py --cham 231 --list <(echo "30"  ) --file ../test.root
python EventDisplay.py --cham 232 --list <(echo "30"  ) --file ../test.root
python EventDisplay.py --cham 233 --list <(echo "411" ) --file ../test.root
python EventDisplay.py --cham 234 --list <(echo "407" ) --file ../test.root
python EventDisplay.py --cham 235 --list <(echo "951" ) --file ../test.root
python EventDisplay.py --cham 236 --list <(echo "132" ) --file ../test.root
python EventDisplay.py --cham 237 --list <(echo "125" ) --file ../test.root
python EventDisplay.py --cham 238 --list <(echo "106" ) --file ../test.root
python EventDisplay.py --cham 239 --list <(echo "59"  ) --file ../test.root
python EventDisplay.py --cham 240 --list <(echo "543" ) --file ../test.root
python EventDisplay.py --cham 241 --list <(echo "21"  ) --file ../test.root
python EventDisplay.py --cham 242 --list <(echo "79"  ) --file ../test.root
python EventDisplay.py --cham 243 --list <(echo "149" ) --file ../test.root
python EventDisplay.py --cham 244 --list <(echo "30"  ) --file ../test.root
python EventDisplay.py --cham 245 --list <(echo "373" ) --file ../test.root
python EventDisplay.py --cham 246 --list <(echo "40"  ) --file ../test.root
python EventDisplay.py --cham 247 --list <(echo "650" ) --file ../test.root
python EventDisplay.py --cham 248 --list <(echo "476" ) --file ../test.root
python EventDisplay.py --cham 249 --list <(echo "719" ) --file ../test.root
python EventDisplay.py --cham 250 --list <(echo "645" ) --file ../test.root
python EventDisplay.py --cham 251 --list <(echo "88"  ) --file ../test.root
python EventDisplay.py --cham 252 --list <(echo "672" ) --file ../test.root
python EventDisplay.py --cham 253 --list <(echo "723" ) --file ../test.root
python EventDisplay.py --cham 254 --list <(echo "240" ) --file ../test.root
python EventDisplay.py --cham 255 --list <(echo "240" ) --file ../test.root
python EventDisplay.py --cham 256 --list <(echo "461" ) --file ../test.root
python EventDisplay.py --cham 257 --list <(echo "1266") --file ../test.root
python EventDisplay.py --cham 258 --list <(echo "303" ) --file ../test.root
python EventDisplay.py --cham 259 --list <(echo "221" ) --file ../test.root
python EventDisplay.py --cham 260 --list <(echo "259" ) --file ../test.root
python EventDisplay.py --cham 261 --list <(echo "273" ) --file ../test.root
python EventDisplay.py --cham 262 --list <(echo "566" ) --file ../test.root
python EventDisplay.py --cham 263 --list <(echo "315" ) --file ../test.root
python EventDisplay.py --cham 264 --list <(echo "266" ) --file ../test.root
python EventDisplay.py --cham 265 --list <(echo "668" ) --file ../test.root
python EventDisplay.py --cham 266 --list <(echo "636" ) --file ../test.root
python EventDisplay.py --cham 267 --list <(echo "595" ) --file ../test.root
python EventDisplay.py --cham 268 --list <(echo "595" ) --file ../test.root
python EventDisplay.py --cham 269 --list <(echo "322" ) --file ../test.root
python EventDisplay.py --cham 270 --list <(echo "462" ) --file ../test.root
python EventDisplay.py --cham 301 --list <(echo "555" ) --file ../test.root
python EventDisplay.py --cham 302 --list <(echo "18"  ) --file ../test.root
python EventDisplay.py --cham 303 --list <(echo "301" ) --file ../test.root
python EventDisplay.py --cham 304 --list <(echo "358" ) --file ../test.root
python EventDisplay.py --cham 305 --list <(echo "199" ) --file ../test.root
python EventDisplay.py --cham 306 --list <(echo "174" ) --file ../test.root
python EventDisplay.py --cham 307 --list <(echo "174" ) --file ../test.root
python EventDisplay.py --cham 308 --list <(echo "569" ) --file ../test.root
python EventDisplay.py --cham 309 --list <(echo "238" ) --file ../test.root
python EventDisplay.py --cham 310 --list <(echo "110" ) --file ../test.root
python EventDisplay.py --cham 311 --list <(echo "8"   ) --file ../test.root
python EventDisplay.py --cham 312 --list <(echo "279" ) --file ../test.root
python EventDisplay.py --cham 313 --list <(echo "180" ) --file ../test.root
python EventDisplay.py --cham 314 --list <(echo "261" ) --file ../test.root
python EventDisplay.py --cham 315 --list <(echo "32"  ) --file ../test.root
python EventDisplay.py --cham 316 --list <(echo "6"   ) --file ../test.root
python EventDisplay.py --cham 317 --list <(echo "6"   ) --file ../test.root
python EventDisplay.py --cham 318 --list <(echo "586" ) --file ../test.root
python EventDisplay.py --cham 319 --list <(echo "18"  ) --file ../test.root
python EventDisplay.py --cham 320 --list <(echo "18"  ) --file ../test.root
python EventDisplay.py --cham 321 --list <(echo "200" ) --file ../test.root
python EventDisplay.py --cham 322 --list <(echo "57"  ) --file ../test.root
python EventDisplay.py --cham 323 --list <(echo "57"  ) --file ../test.root
python EventDisplay.py --cham 324 --list <(echo "728" ) --file ../test.root
python EventDisplay.py --cham 325 --list <(echo "728" ) --file ../test.root
python EventDisplay.py --cham 326 --list <(echo "341" ) --file ../test.root
python EventDisplay.py --cham 327 --list <(echo "341" ) --file ../test.root
python EventDisplay.py --cham 328 --list <(echo "174" ) --file ../test.root
python EventDisplay.py --cham 329 --list <(echo "376" ) --file ../test.root
python EventDisplay.py --cham 330 --list <(echo "1059") --file ../test.root
python EventDisplay.py --cham 331 --list <(echo "306" ) --file ../test.root
python EventDisplay.py --cham 332 --list <(echo "614" ) --file ../test.root
python EventDisplay.py --cham 333 --list <(echo "86"  ) --file ../test.root
python EventDisplay.py --cham 334 --list <(echo "6"   ) --file ../test.root
python EventDisplay.py --cham 335 --list <(echo "6"   ) --file ../test.root
python EventDisplay.py --cham 336 --list <(echo "136" ) --file ../test.root
python EventDisplay.py --cham 337 --list <(echo "145" ) --file ../test.root
python EventDisplay.py --cham 338 --list <(echo "145" ) --file ../test.root
python EventDisplay.py --cham 339 --list <(echo "1208") --file ../test.root
python EventDisplay.py --cham 340 --list <(echo "21"  ) --file ../test.root
python EventDisplay.py --cham 341 --list <(echo "400" ) --file ../test.root
python EventDisplay.py --cham 342 --list <(echo "4"   ) --file ../test.root
python EventDisplay.py --cham 343 --list <(echo "4"   ) --file ../test.root
python EventDisplay.py --cham 344 --list <(echo "1060") --file ../test.root
python EventDisplay.py --cham 345 --list <(echo "140" ) --file ../test.root
python EventDisplay.py --cham 346 --list <(echo "140" ) --file ../test.root
python EventDisplay.py --cham 347 --list <(echo "725" ) --file ../test.root
python EventDisplay.py --cham 348 --list <(echo "1203") --file ../test.root
python EventDisplay.py --cham 349 --list <(echo "181" ) --file ../test.root
python EventDisplay.py --cham 350 --list <(echo "131" ) --file ../test.root
python EventDisplay.py --cham 351 --list <(echo "86"  ) --file ../test.root
python EventDisplay.py --cham 352 --list <(echo "23"  ) --file ../test.root
python EventDisplay.py --cham 353 --list <(echo "23"  ) --file ../test.root
python EventDisplay.py --cham 354 --list <(echo "143" ) --file ../test.root
python EventDisplay.py --cham 355 --list <(echo "158" ) --file ../test.root
python EventDisplay.py --cham 356 --list <(echo "1319") --file ../test.root
python EventDisplay.py --cham 357 --list <(echo "515" ) --file ../test.root
python EventDisplay.py --cham 358 --list <(echo "366" ) --file ../test.root
python EventDisplay.py --cham 359 --list <(echo "490" ) --file ../test.root
python EventDisplay.py --cham 360 --list <(echo "1064") --file ../test.root
python EventDisplay.py --cham 361 --list <(echo "8"   ) --file ../test.root
python EventDisplay.py --cham 362 --list <(echo "547" ) --file ../test.root
python EventDisplay.py --cham 363 --list <(echo "547" ) --file ../test.root
python EventDisplay.py --cham 364 --list <(echo "279" ) --file ../test.root
python EventDisplay.py --cham 365 --list <(echo "432" ) --file ../test.root
python EventDisplay.py --cham 366 --list <(echo "432" ) --file ../test.root
python EventDisplay.py --cham 368 --list <(echo "692" ) --file ../test.root
python EventDisplay.py --cham 369 --list <(echo "32"  ) --file ../test.root
python EventDisplay.py --cham 370 --list <(echo "286" ) --file ../test.root
python EventDisplay.py --cham 371 --list <(echo "23"  ) --file ../test.root
python EventDisplay.py --cham 372 --list <(echo "638" ) --file ../test.root
python EventDisplay.py --cham 373 --list <(echo "719" ) --file ../test.root
python EventDisplay.py --cham 374 --list <(echo "672" ) --file ../test.root
python EventDisplay.py --cham 375 --list <(echo "177" ) --file ../test.root
python EventDisplay.py --cham 376 --list <(echo "1258") --file ../test.root
python EventDisplay.py --cham 377 --list <(echo "95"  ) --file ../test.root
python EventDisplay.py --cham 379 --list <(echo "28"  ) --file ../test.root
python EventDisplay.py --cham 380 --list <(echo "187" ) --file ../test.root
python EventDisplay.py --cham 381 --list <(echo "216" ) --file ../test.root
python EventDisplay.py --cham 382 --list <(echo "273" ) --file ../test.root
python EventDisplay.py --cham 383 --list <(echo "1348") --file ../test.root
python EventDisplay.py --cham 384 --list <(echo "1234") --file ../test.root
python EventDisplay.py --cham 387 --list <(echo "977" ) --file ../test.root
python EventDisplay.py --cham 388 --list <(echo "376" ) --file ../test.root
python EventDisplay.py --cham 389 --list <(echo "418" ) --file ../test.root
python EventDisplay.py --cham 390 --list <(echo "79"  ) --file ../test.root
python EventDisplay.py --cham 391 --list <(echo "1198") --file ../test.root
python EventDisplay.py --cham 393 --list <(echo "34"  ) --file ../test.root
python EventDisplay.py --cham 394 --list <(echo "588" ) --file ../test.root
python EventDisplay.py --cham 395 --list <(echo "964" ) --file ../test.root
python EventDisplay.py --cham 396 --list <(echo "199" ) --file ../test.root
python EventDisplay.py --cham 397 --list <(echo "40"  ) --file ../test.root
python EventDisplay.py --cham 398 --list <(echo "3"   ) --file ../test.root
python EventDisplay.py --cham 399 --list <(echo "1018") --file ../test.root
python EventDisplay.py --cham 400 --list <(echo "510" ) --file ../test.root
python EventDisplay.py --cham 401 --list <(echo "110" ) --file ../test.root
python EventDisplay.py --cham 402 --list <(echo "1140") --file ../test.root
python EventDisplay.py --cham 403 --list <(echo "932" ) --file ../test.root
python EventDisplay.py --cham 404 --list <(echo "1021") --file ../test.root
python EventDisplay.py --cham 405 --list <(echo "60"  ) --file ../test.root
python EventDisplay.py --cham 406 --list <(echo "1162") --file ../test.root
python EventDisplay.py --cham 407 --list <(echo "163" ) --file ../test.root
python EventDisplay.py --cham 408 --list <(echo "200" ) --file ../test.root
python EventDisplay.py --cham 409 --list <(echo "18"  ) --file ../test.root
python EventDisplay.py --cham 410 --list <(echo "301" ) --file ../test.root
python EventDisplay.py --cham 411 --list <(echo "174" ) --file ../test.root
python EventDisplay.py --cham 412 --list <(echo "174" ) --file ../test.root
python EventDisplay.py --cham 413 --list <(echo "238" ) --file ../test.root
python EventDisplay.py --cham 414 --list <(echo "8"   ) --file ../test.root
python EventDisplay.py --cham 415 --list <(echo "180" ) --file ../test.root
python EventDisplay.py --cham 416 --list <(echo "6"   ) --file ../test.root
python EventDisplay.py --cham 417 --list <(echo "6"   ) --file ../test.root
python EventDisplay.py --cham 418 --list <(echo "18"  ) --file ../test.root
python EventDisplay.py --cham 419 --list <(echo "57"  ) --file ../test.root
python EventDisplay.py --cham 420 --list <(echo "57"  ) --file ../test.root
python EventDisplay.py --cham 421 --list <(echo "341" ) --file ../test.root
python EventDisplay.py --cham 422 --list <(echo "174" ) --file ../test.root
python EventDisplay.py --cham 423 --list <(echo "376" ) --file ../test.root
python EventDisplay.py --cham 424 --list <(echo "306" ) --file ../test.root
python EventDisplay.py --cham 425 --list <(echo "6"   ) --file ../test.root
python EventDisplay.py --cham 426 --list <(echo "6"   ) --file ../test.root
python EventDisplay.py --cham 427 --list <(echo "145" ) --file ../test.root
python EventDisplay.py --cham 428 --list <(echo "145" ) --file ../test.root
python EventDisplay.py --cham 429 --list <(echo "1208") --file ../test.root
python EventDisplay.py --cham 430 --list <(echo "21"  ) --file ../test.root
python EventDisplay.py --cham 431 --list <(echo "400" ) --file ../test.root
python EventDisplay.py --cham 432 --list <(echo "4"   ) --file ../test.root
python EventDisplay.py --cham 433 --list <(echo "193" ) --file ../test.root
python EventDisplay.py --cham 434 --list <(echo "1060") --file ../test.root
python EventDisplay.py --cham 435 --list <(echo "140" ) --file ../test.root
python EventDisplay.py --cham 436 --list <(echo "140" ) --file ../test.root
python EventDisplay.py --cham 437 --list <(echo "725" ) --file ../test.root
python EventDisplay.py --cham 438 --list <(echo "1031") --file ../test.root
python EventDisplay.py --cham 439 --list <(echo "181" ) --file ../test.root
python EventDisplay.py --cham 440 --list <(echo "131" ) --file ../test.root
python EventDisplay.py --cham 441 --list <(echo "86"  ) --file ../test.root
python EventDisplay.py --cham 442 --list <(echo "286" ) --file ../test.root
python EventDisplay.py --cham 443 --list <(echo "301" ) --file ../test.root
python EventDisplay.py --cham 444 --list <(echo "143" ) --file ../test.root
python EventDisplay.py --cham 445 --list <(echo "60"  ) --file ../test.root
python EventDisplay.py --cham 446 --list <(echo "791" ) --file ../test.root
python EventDisplay.py --cham 447 --list <(echo "34"  ) --file ../test.root
python EventDisplay.py --cham 448 --list <(echo "366" ) --file ../test.root
python EventDisplay.py --cham 449 --list <(echo "490" ) --file ../test.root
python EventDisplay.py --cham 450 --list <(echo "28"  ) --file ../test.root
python EventDisplay.py --cham 451 --list <(echo "8"   ) --file ../test.root
python EventDisplay.py --cham 452 --list <(echo "310" ) --file ../test.root
python EventDisplay.py --cham 453 --list <(echo "547" ) --file ../test.root
python EventDisplay.py --cham 454 --list <(echo "279" ) --file ../test.root
python EventDisplay.py --cham 455 --list <(echo "432" ) --file ../test.root
python EventDisplay.py --cham 456 --list <(echo "432" ) --file ../test.root
python EventDisplay.py --cham 457 --list <(echo "247" ) --file ../test.root
python EventDisplay.py --cham 458 --list <(echo "247" ) --file ../test.root
python EventDisplay.py --cham 459 --list <(echo "32"  ) --file ../test.root
python EventDisplay.py --cham 460 --list <(echo "286" ) --file ../test.root
python EventDisplay.py --cham 461 --list <(echo "23"  ) --file ../test.root
python EventDisplay.py --cham 462 --list <(echo "359" ) --file ../test.root
python EventDisplay.py --cham 463 --list <(echo "561" ) --file ../test.root
python EventDisplay.py --cham 464 --list <(echo "301" ) --file ../test.root
python EventDisplay.py --cham 465 --list <(echo "174" ) --file ../test.root
python EventDisplay.py --cham 466 --list <(echo "174" ) --file ../test.root
python EventDisplay.py --cham 467 --list <(echo "238" ) --file ../test.root
python EventDisplay.py --cham 468 --list <(echo "8"   ) --file ../test.root
python EventDisplay.py --cham 469 --list <(echo "180" ) --file ../test.root
python EventDisplay.py --cham 470 --list <(echo "6"   ) --file ../test.root
python EventDisplay.py --cham 471 --list <(echo "6"   ) --file ../test.root
python EventDisplay.py --cham 472 --list <(echo "18"  ) --file ../test.root
python EventDisplay.py --cham 473 --list <(echo "57"  ) --file ../test.root
python EventDisplay.py --cham 474 --list <(echo "57"  ) --file ../test.root
python EventDisplay.py --cham 475 --list <(echo "341" ) --file ../test.root
python EventDisplay.py --cham 476 --list <(echo "389" ) --file ../test.root
python EventDisplay.py --cham 477 --list <(echo "376" ) --file ../test.root
python EventDisplay.py --cham 478 --list <(echo "306" ) --file ../test.root
python EventDisplay.py --cham 479 --list <(echo "6"   ) --file ../test.root
python EventDisplay.py --cham 480 --list <(echo "6"   ) --file ../test.root
python EventDisplay.py --cham 481 --list <(echo "145" ) --file ../test.root
python EventDisplay.py --cham 482 --list <(echo "18"  ) --file ../test.root
python EventDisplay.py --cham 483 --list <(echo "1208") --file ../test.root
python EventDisplay.py --cham 484 --list <(echo "21"  ) --file ../test.root
python EventDisplay.py --cham 485 --list <(echo "400" ) --file ../test.root
python EventDisplay.py --cham 486 --list <(echo "4"   ) --file ../test.root
python EventDisplay.py --cham 487 --list <(echo "193" ) --file ../test.root
python EventDisplay.py --cham 488 --list <(echo "1060") --file ../test.root
python EventDisplay.py --cham 489 --list <(echo "140" ) --file ../test.root
python EventDisplay.py --cham 490 --list <(echo "140" ) --file ../test.root
python EventDisplay.py --cham 491 --list <(echo "725" ) --file ../test.root
python EventDisplay.py --cham 492 --list <(echo "1031") --file ../test.root
python EventDisplay.py --cham 493 --list <(echo "181" ) --file ../test.root
python EventDisplay.py --cham 494 --list <(echo "131" ) --file ../test.root
python EventDisplay.py --cham 495 --list <(echo "86"  ) --file ../test.root
python EventDisplay.py --cham 496 --list <(echo "23"  ) --file ../test.root
python EventDisplay.py --cham 497 --list <(echo "23"  ) --file ../test.root
python EventDisplay.py --cham 498 --list <(echo "143" ) --file ../test.root
python EventDisplay.py --cham 499 --list <(echo "60"  ) --file ../test.root
python EventDisplay.py --cham 500 --list <(echo "410" ) --file ../test.root
python EventDisplay.py --cham 501 --list <(echo "142" ) --file ../test.root
python EventDisplay.py --cham 502 --list <(echo "366" ) --file ../test.root
python EventDisplay.py --cham 503 --list <(echo "490" ) --file ../test.root
python EventDisplay.py --cham 504 --list <(echo "28"  ) --file ../test.root
python EventDisplay.py --cham 505 --list <(echo "8"   ) --file ../test.root
python EventDisplay.py --cham 506 --list <(echo "991" ) --file ../test.root
python EventDisplay.py --cham 507 --list <(echo "547" ) --file ../test.root
python EventDisplay.py --cham 508 --list <(echo "279" ) --file ../test.root
python EventDisplay.py --cham 509 --list <(echo "432" ) --file ../test.root
python EventDisplay.py --cham 510 --list <(echo "432" ) --file ../test.root
python EventDisplay.py --cham 511 --list <(echo "247" ) --file ../test.root
python EventDisplay.py --cham 512 --list <(echo "692" ) --file ../test.root
python EventDisplay.py --cham 513 --list <(echo "32"  ) --file ../test.root
python EventDisplay.py --cham 514 --list <(echo "286" ) --file ../test.root
python EventDisplay.py --cham 515 --list <(echo "23"  ) --file ../test.root
python EventDisplay.py --cham 516 --list <(echo "359" ) --file ../test.root
python EventDisplay.py --cham 517 --list <(echo "561" ) --file ../test.root
python EventDisplay.py --cham 518 --list <(echo "301" ) --file ../test.root
python EventDisplay.py --cham 519 --list <(echo "174" ) --file ../test.root
python EventDisplay.py --cham 520 --list <(echo "174" ) --file ../test.root
python EventDisplay.py --cham 521 --list <(echo "238" ) --file ../test.root
python EventDisplay.py --cham 522 --list <(echo "8"   ) --file ../test.root
python EventDisplay.py --cham 523 --list <(echo "180" ) --file ../test.root
python EventDisplay.py --cham 524 --list <(echo "6"   ) --file ../test.root
python EventDisplay.py --cham 525 --list <(echo "6"   ) --file ../test.root
python EventDisplay.py --cham 526 --list <(echo "18"  ) --file ../test.root
python EventDisplay.py --cham 527 --list <(echo "57"  ) --file ../test.root
python EventDisplay.py --cham 528 --list <(echo "417" ) --file ../test.root
python EventDisplay.py --cham 529 --list <(echo "341" ) --file ../test.root
python EventDisplay.py --cham 530 --list <(echo "389" ) --file ../test.root
python EventDisplay.py --cham 531 --list <(echo "376" ) --file ../test.root
python EventDisplay.py --cham 532 --list <(echo "306" ) --file ../test.root
python EventDisplay.py --cham 533 --list <(echo "6"   ) --file ../test.root
python EventDisplay.py --cham 534 --list <(echo "6"   ) --file ../test.root
python EventDisplay.py --cham 535 --list <(echo "145" ) --file ../test.root
python EventDisplay.py --cham 536 --list <(echo "18"  ) --file ../test.root
python EventDisplay.py --cham 537 --list <(echo "1208") --file ../test.root
python EventDisplay.py --cham 538 --list <(echo "21"  ) --file ../test.root
python EventDisplay.py --cham 539 --list <(echo "400" ) --file ../test.root
python EventDisplay.py --cham 540 --list <(echo "4"   ) --file ../test.root
python EventDisplay.py --cham 541 --list <(echo "262" ) --file ../test.root
python EventDisplay.py --cham 542 --list <(echo "1060") --file ../test.root
python EventDisplay.py --cham 543 --list <(echo "140" ) --file ../test.root
python EventDisplay.py --cham 544 --list <(echo "140" ) --file ../test.root
python EventDisplay.py --cham 545 --list <(echo "110" ) --file ../test.root
python EventDisplay.py --cham 546 --list <(echo "1203") --file ../test.root
python EventDisplay.py --cham 547 --list <(echo "181" ) --file ../test.root
python EventDisplay.py --cham 548 --list <(echo "131" ) --file ../test.root
python EventDisplay.py --cham 549 --list <(echo "86"  ) --file ../test.root
python EventDisplay.py --cham 550 --list <(echo "23"  ) --file ../test.root
python EventDisplay.py --cham 551 --list <(echo "23"  ) --file ../test.root
python EventDisplay.py --cham 552 --list <(echo "760" ) --file ../test.root
python EventDisplay.py --cham 553 --list <(echo "158" ) --file ../test.root
python EventDisplay.py --cham 554 --list <(echo "410" ) --file ../test.root
python EventDisplay.py --cham 555 --list <(echo "142" ) --file ../test.root
python EventDisplay.py --cham 556 --list <(echo "266" ) --file ../test.root
python EventDisplay.py --cham 557 --list <(echo "490" ) --file ../test.root
python EventDisplay.py --cham 558 --list <(echo "728" ) --file ../test.root
python EventDisplay.py --cham 559 --list <(echo "8"   ) --file ../test.root
python EventDisplay.py --cham 560 --list <(echo "991" ) --file ../test.root
python EventDisplay.py --cham 561 --list <(echo "547" ) --file ../test.root
python EventDisplay.py --cham 562 --list <(echo "174" ) --file ../test.root
python EventDisplay.py --cham 563 --list <(echo "432" ) --file ../test.root
python EventDisplay.py --cham 565 --list <(echo "1296") --file ../test.root
python EventDisplay.py --cham 566 --list <(echo "692" ) --file ../test.root
python EventDisplay.py --cham 567 --list <(echo "32"  ) --file ../test.root
python EventDisplay.py --cham 568 --list <(echo "286" ) --file ../test.root
python EventDisplay.py --cham 569 --list <(echo "23"  ) --file ../test.root
python EventDisplay.py --cham 570 --list <(echo "638" ) --file ../test.root

#python EventDisplay.py --cham   1 --list <(echo "223" ) --file ../test.root
#python EventDisplay.py --cham  37 --list <(echo "951" ) --file ../test.root
#python EventDisplay.py --cham  73 --list <(echo "361" ) --file ../test.root
#python EventDisplay.py --cham 109 --list <(echo "223" ) --file ../test.root
#python EventDisplay.py --cham 127 --list <(echo "160" ) --file ../test.root
#python EventDisplay.py --cham 163 --list <(echo "223" ) --file ../test.root
#python EventDisplay.py --cham 181 --list <(echo "160" ) --file ../test.root
#python EventDisplay.py --cham 217 --list <(echo "223" ) --file ../test.root
#python EventDisplay.py --cham 235 --list <(echo "951" ) --file ../test.root
#python EventDisplay.py --cham 301 --list <(echo "555" ) --file ../test.root
#python EventDisplay.py --cham 337 --list <(echo "145" ) --file ../test.root
#python EventDisplay.py --cham 373 --list <(echo "719" ) --file ../test.root
#python EventDisplay.py --cham 409 --list <(echo "18"  ) --file ../test.root
#python EventDisplay.py --cham 427 --list <(echo "145" ) --file ../test.root
#python EventDisplay.py --cham 463 --list <(echo "561" ) --file ../test.root
#python EventDisplay.py --cham 481 --list <(echo "145" ) --file ../test.root
#python EventDisplay.py --cham 517 --list <(echo "561" ) --file ../test.root
#python EventDisplay.py --cham 535 --list <(echo "145" ) --file ../test.root
